/** @deprecated Import from `@/lib/officialResultTerminalSync` instead. */
export {
  type OfficialResultDsqSyncResult,
  type OfficialResultTerminalSyncResult,
  TERMINAL_OFFICIAL_STATUSES,
  TERMINAL_DAY_OPS_STATUSES,
  truncateDsqRemarks,
  truncateTerminalRemarks,
  isDsqOnlyOfficialRow,
  isTerminalOnlyOfficialRow,
  isParticipantDsqForRound,
  resolveParticipantTerminalStatusForRound,
  ensureOfficialResultForRound,
  applyOfficialRowForParticipantDsq,
  applyOfficialRowForParticipantTerminal,
  clearOfficialRowAfterDsqRevert,
  clearOfficialRowAfterTerminalRevert,
  reconcileOfficialDsqRowsForHeat,
  reconcileOfficialTerminalRowsForHeat,
  toOfficialMarshalParticipantRef,
  syncOfficialDsqRowFromSnapshot,
  syncOfficialTerminalRowFromSnapshot,
} from "@/lib/officialResultTerminalSync";
