name: "Auto-merge PRs with label"

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge
        uses: pascalgn/automerge-action@v0.14.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          # Auto-merge when PR has label 'automerge' or is a dependency PR from dependabot
          labels: 'automerge,dependencies'
          allow_no_review: false
