name: "Conventional Commit Lint"

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Install commitlint
        run: npm install --save-dev @commitlint/config-conventional @commitlint/cli
      - name: Validate commits
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
